FROM python:3-slim

RUN apt-get update && apt-get install -y build-essential python3-dev && rm -rf /var/lib/apt/lists/*

RUN useradd sungather

WORKDIR /usr/src/sungather

COPY requirements.txt ./
RUN pip install --no-cache-dir --upgrade -r requirements.txt

COPY SunGather/ .

VOLUME /logs
VOLUME /config
VOLUME /registers
COPY SunGather/config-example.yaml /config/config.yaml
COPY SunGather/registers-sungrow.yaml /registers/registers-sungrow.yaml
USER sungather

CMD [ "python", "sungather.py", "-c", "/config/config.yaml", "-r", "/registers/registers-sungrow.yaml", "-l", "/logs/" ]

